version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Docker/frontend.Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Docker/backend.Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/incomeexpenses
      - PORT=5001
    volumes:
      - ./Backend:/app
      - /app/node_modules
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=incomeexpenses
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 