services:
  frontend:
    build:
      context: .
      dockerfile: Docker/frontend.Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:5001
      - ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://localhost:4173
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Docker/backend.Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://app:app@postgres:5432/income_expense?schema=public
      - PORT=5001
    volumes:
      - ./Backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: ie-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: income_expense
    ports:
      - "5432:5432"       # sadece lokal geliştirme için
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d income_expense"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: 